"""Agregar columna password_hash a usuario y verif

Revision ID: f4e4eb1292ee
Revises: ea8adbf6b892
Create Date: 2024-11-24 20:16:07.799230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e4eb1292ee'
down_revision = 'ea8adbf6b892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('electronicmail', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['electronicmail'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('electronicmail')

    # ### end Alembic commands ###
